name: Run server
on: workflow_dispatch

jobs:
  run_server:
    runs-on: ubuntu-latest
    container: archlinux
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: |
          pacman --noconfirm -Syu sudo
          sudo pacman --noconfirm -S python unzip
          cd $GITHUB_WORKSPACE
          sudo unzip .venv.zip
          source .venv/bin/activate
          python manage.py runserver
