name: Run server
on: workflow_dispatch

jobs:
  run_server:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: |
          pacman --noconfirm -Syu sudo
          sudo pacman --noconfirm -S python python-pip unzip nginx postgresql memcached
          #sudo pip install pipreqs
          sudo pip install django django-cleanup django-cachalot gunicorn pillow
          cd $GITHUB_WORKSPACE
          #sudo unzip .venv.zip > /dev/null
          #sudo pipreqs .venv
          #sudo chmod -R 755 .venv
          #source .venv/bin/activate
      - name: PostgreSQL Setup
        run: |
          su postgres -c 'initdb -D /var/lib/postgres/data'
          echo 'Running PostgreSQL server...'
          sudo mkdir -p /run/postgresql
          sudo sudo chown -R postgres:postgres /run/postgresql/
          su postgres -c '/usr/bin/postgres -D /var/lib/postgres/data &'
          #sleep 10
          #echo 'Creating database...'
          #su postgres -c 'createdb postgres'
      - name: Run memcached
        run: |
          sudo memcached -u &
      - name: Prepare Server
        run: |
          sudo mkdir logs
      - name: Run Server
        run: |
          python manage.py runserver
