name: Run server
on: workflow_dispatch

jobs:
  run_server:
    runs-on: ubuntu-latest
    container: archlinux
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: |
          pacman --noconfirm -Syu sudo
          sudo pacman --noconfirm -S python python-pip unzip
          sudo pip install pipreqs
          cd $GITHUB_WORKSPACE
          sudo unzip .venv.zip > /dev/null
          sudo pipreqs .venv
          sudo chmod -R 755 .venv
          source .venv/bin/activate
          .venv/bin/python manage.py runserver
